@startuml kattis
scale 2
title "kattis"
class  Kattis{
    ...Class Methods...
    +__init__(): None
    +read_input(): None
    +data(): None
    +answer(): Any 
    +solve(): None
    +print_answer(): None
}
@enduml