@startuml Main
scale 2
title "UML Class Diagram"
class main{
    ..Class Variables..
    -_data: list
    -_num: int
    -_denom: int
    -_fraction_obj: Fraction
    ..Class Methods..
    +userFractions(): None
    +set_user_fractions(): None
    +getNum(): int
    +getDenom(): int
    +getData(): list
    +MixNum(): None
    +set_poly_elements(): None
    +answer(): None
...Static Method...
    +main(): None
}
@enduml